#include "kyma/interpreter.hpp"
#include <chrono>
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>
#include <thread>
#if defined(__unix__) || defined(__APPLE__) 
#include <netdb.h>
#include <sys/socket.h>
#include <unistd.h>
#endif

namespace kyma {
namespace { bool has(const std::vector<std::string>& m,const std::string& x){return std::find(m.begin(),m.end(),x)!=m.end();}
std::string httpGetText(const std::string& url){
#if !defined(__unix__) && !defined(__APPLE__)
 throw KymaError({"httpGet is unavailable on this platform",{1,1},false});
#else
 if(url.rfind("http://",0)!=0)throw KymaError({"httpGet currently supports only http:// URLs (TLS is not included)",{1,1},false});
 auto rest=url.substr(7);auto slash=rest.find('/');auto hostPort=rest.substr(0,slash);auto path=slash==std::string::npos?"/":rest.substr(slash);std::string host=hostPort;std::string port="80";auto colon=hostPort.rfind(':');if(colon!=std::string::npos){host=hostPort.substr(0,colon);port=hostPort.substr(colon+1);}
 addrinfo hints{};hints.ai_socktype=SOCK_STREAM;hints.ai_family=AF_UNSPEC;addrinfo* result=nullptr;if(getaddrinfo(host.c_str(),port.c_str(),&hints,&result)!=0)throw KymaError({"could not resolve host '"+host+"'",{1,1},false});int fd=-1;for(auto* a=result;a;a=a->ai_next){fd=socket(a->ai_family,a->ai_socktype,a->ai_protocol);if(fd>=0&&connect(fd,a->ai_addr,a->ai_addrlen)==0)break;if(fd>=0){close(fd);fd=-1;}}freeaddrinfo(result);if(fd<0)throw KymaError({"could not connect to '"+host+"'",{1,1},false});std::string request="GET "+path+" HTTP/1.1\r\nHost: "+host+"\r\nConnection: close\r\n\r\n";if(send(fd,request.data(),request.size(),0)<0){close(fd);throw KymaError({"failed to send HTTP request",{1,1},false});}std::string response;char buffer[4096];for(;;){auto n=recv(fd,buffer,sizeof(buffer),0);if(n<=0)break;response.append(buffer,static_cast<size_t>(n));}close(fd);auto split=response.find("\r\n\r\n");return split==std::string::npos?response:response.substr(split+4);
#endif
} }
Interpreter::Interpreter():global(std::make_shared<Environment>()),environment(global){
 auto print=std::make_shared<Function>();print->native=true;print->nativeCall=[](const std::vector<Value>& a){for(size_t i=0;i<a.size();++i){if(i)std::cout<<' ';std::cout<<a[i].display();}std::cout<<'\n';return Value();};global->define("print",Value(print),false);
 auto type=std::make_shared<Function>();type->native=true;type->nativeCall=[](const std::vector<Value>& a){return a.empty()?Value(std::string("void")):Value(a[0].typeName());};global->define("typeOf",Value(type),false);
 auto collect=std::make_shared<Function>();collect->native=true;collect->nativeCall=[this](const std::vector<Value>&){objectHeap.collect({global.get(),environment.get()});return Value();};global->define("collectGarbage",Value(collect),false);
 auto stats=std::make_shared<Function>();stats->native=true;stats->nativeCall=[this](const std::vector<Value>&){return Value(std::string("heap: ")+std::to_string(objectHeap.live())+" live, "+std::to_string(objectHeap.collections())+" collections");};global->define("gcStats",Value(stats),false);
 auto length=std::make_shared<Function>();length->native=true;length->nativeCall=[](const std::vector<Value>&a){if(a.size()!=1)throw KymaError({"len expects one argument",{1,1},false});if(auto s=std::get_if<std::string>(&a[0].data))return Value(static_cast<int64_t>(s->size()));if(auto x=std::get_if<ArrayPtr>(&a[0].data))return Value(static_cast<int64_t>((*x)->elements.size()));if(auto o=std::get_if<ObjectPtr>(&a[0].data))return Value(static_cast<int64_t>((*o)->fields.size()));throw KymaError({"len requires a string, array, or object",{1,1},false});};global->define("len",Value(length),false);
 auto push=std::make_shared<Function>();push->native=true;push->nativeCall=[](const std::vector<Value>&a){if(a.size()!=2||!std::holds_alternative<ArrayPtr>(a[0].data))throw KymaError({"push expects an array and a value",{1,1},false});std::get<ArrayPtr>(a[0].data)->elements.push_back(a[1]);return Value();};global->define("push",Value(push),false);
 auto pop=std::make_shared<Function>();pop->native=true;pop->nativeCall=[](const std::vector<Value>&a){if(a.size()!=1||!std::holds_alternative<ArrayPtr>(a[0].data))throw KymaError({"pop expects an array",{1,1},false});auto array=std::get<ArrayPtr>(a[0].data);if(array->elements.empty())return Value();auto v=array->elements.back();array->elements.pop_back();return v;};global->define("pop",Value(pop),false);
 auto keys=std::make_shared<Function>();keys->native=true;keys->nativeCall=[this](const std::vector<Value>&a){if(a.size()!=1||!std::holds_alternative<ObjectPtr>(a[0].data))throw KymaError({"keys expects an object",{1,1},false});auto array=objectHeap.allocateArray();for(const auto&[name,value]:std::get<ObjectPtr>(a[0].data)->fields)array->elements.emplace_back(name);return Value(array);};global->define("keys",Value(keys),false);
 auto read=std::make_shared<Function>();read->native=true;read->nativeCall=[](const std::vector<Value>&a){if(a.size()!=1||!std::holds_alternative<std::string>(a[0].data))throw KymaError({"readFile expects a path",{1,1},false});std::ifstream file(std::get<std::string>(a[0].data));if(!file)throw KymaError({"could not read file",{1,1},false});std::stringstream text;text<<file.rdbuf();return Value(text.str());};global->define("readFile",Value(read),false);
 auto write=std::make_shared<Function>();write->native=true;write->nativeCall=[](const std::vector<Value>&a){if(a.size()!=2||!std::holds_alternative<std::string>(a[0].data)||!std::holds_alternative<std::string>(a[1].data))throw KymaError({"writeFile expects path and string content",{1,1},false});std::ofstream file(std::get<std::string>(a[0].data));if(!file)throw KymaError({"could not write file",{1,1},false});file<<std::get<std::string>(a[1].data);return Value();};global->define("writeFile",Value(write),false);
 auto run=std::make_shared<Function>();run->native=true;run->nativeCall=[](const std::vector<Value>&a){if(a.size()!=1||!std::holds_alternative<std::string>(a[0].data))throw KymaError({"processRun expects a shell command string",{1,1},false});return Value(static_cast<int64_t>(std::system(std::get<std::string>(a[0].data).c_str())));};global->define("processRun",Value(run),false);
 auto environment=std::make_shared<Function>();environment->native=true;environment->nativeCall=[](const std::vector<Value>&a){if(a.size()!=1||!std::holds_alternative<std::string>(a[0].data))throw KymaError({"processEnv expects a variable name",{1,1},false});auto* value=std::getenv(std::get<std::string>(a[0].data).c_str());return value?Value(std::string(value)):Value();};global->define("processEnv",Value(environment),false);
 auto sleep=std::make_shared<Function>();sleep->native=true;sleep->nativeCall=[](const std::vector<Value>&a){if(a.size()!=1||!std::holds_alternative<int64_t>(a[0].data))throw KymaError({"sleep expects milliseconds",{1,1},false});std::this_thread::sleep_for(std::chrono::milliseconds(std::get<int64_t>(a[0].data)));return Value();};global->define("sleep",Value(sleep),false);
 auto get=std::make_shared<Function>();get->native=true;get->nativeCall=[](const std::vector<Value>&a){if(a.size()!=1||!std::holds_alternative<std::string>(a[0].data))throw KymaError({"httpGet expects a URL string",{1,1},false});return Value(httpGetText(std::get<std::string>(a[0].data)));};global->define("httpGet",Value(get),false);
}
Value Interpreter::execute(const std::vector<StmtPtr>& program){Value last;for(auto&s:program){exec(s);objectHeap.maybeCollect({global.get(),environment.get()});if(flow.kind!=Flow::None)break;}return last;}
void Interpreter::execute(const StmtPtr& s){exec(s);} Value Interpreter::evaluate(const ExprPtr&e){return eval(e);}
void Interpreter::execBlock(const BlockStmt& b,std::shared_ptr<Environment> env){auto old=environment;environment=std::move(env);for(auto&s:b.statements){exec(s);if(flow.kind!=Flow::None)break;}environment=old;}
void Interpreter::exec(const StmtPtr& s){std::visit([this](const auto& n){using T=std::decay_t<decltype(n)>;
 if constexpr(std::is_same_v<T,VarDecl>){Value v=n.initializer?eval(n.initializer):Value();environment->define(n.name,v,n.mutableBinding);}
 else if constexpr(std::is_same_v<T,ExprStmt>){eval(n.expression);}
 else if constexpr(std::is_same_v<T,BlockStmt>){execBlock(n,std::make_shared<Environment>(environment));}
 else if constexpr(std::is_same_v<T,IfStmt>){if(eval(n.condition).isTruthy())exec(n.thenBranch);else if(n.elseBranch)exec(n.elseBranch);}
 else if constexpr(std::is_same_v<T,WhileStmt>){++loopDepth;while(eval(n.condition).isTruthy()){exec(n.body);if(flow.kind==Flow::Return)break;if(flow.kind==Flow::Break){if(flow.label.empty()||flow.label==n.label)flow={};else break;break;}if(flow.kind==Flow::Continue){if(flow.label.empty()||flow.label==n.label)flow={};else break;}}--loopDepth;}
 else if constexpr(std::is_same_v<T,LoopStmt>){if(n.initializer)exec(n.initializer);++loopDepth;while(!n.condition||eval(n.condition).isTruthy()){exec(n.body);if(flow.kind==Flow::Return)break;if(flow.kind==Flow::Break){if(flow.label.empty()||flow.label==n.label)flow={};else break;break;}if(flow.kind==Flow::Continue){if(flow.label.empty()||flow.label==n.label)flow={};else break;}if(n.increment)eval(n.increment);}--loopDepth;}
 else if constexpr(std::is_same_v<T,BreakStmt>){if(loopDepth==0)throw KymaError({"break must be inside a loop",{1,1},false});flow={Flow::Break,{},n.label};}
 else if constexpr(std::is_same_v<T,ContinueStmt>){if(loopDepth==0)throw KymaError({"continue must be inside a loop",{1,1},false});flow={Flow::Continue,{},n.label};}
 else if constexpr(std::is_same_v<T,ReturnStmt>){flow={Flow::Return,n.value?eval(n.value):Value(),""};}
 else if constexpr(std::is_same_v<T,FunctionDecl>){auto f=std::make_shared<Function>();f->declaration=n;f->closure=environment;environment->define(n.name,Value(f),false);}
 else if constexpr(std::is_same_v<T,ClassDecl>){auto c=std::make_shared<Class>();c->declaration=n; if(!n.parent.empty()){auto v=environment->get(n.parent).value;if(!std::holds_alternative<ClassPtr>(v.data))throw KymaError({"'"+n.parent+"' is not a class",{1,1},false});c->parent=std::get<ClassPtr>(v.data);}for(auto&field:n.fields)if(has(field.modifiers,"static"))c->staticFields[field.name]=field.initializer?eval(field.initializer):Value();for(const auto&m:n.methods){auto f=std::make_shared<Function>();f->declaration=m;f->closure=environment;c->methods[m.name]=f;}environment->define(n.name,Value(c),false);}
 else if constexpr(std::is_same_v<T,InterfaceDecl>){/* interfaces are compile-time contracts in v0.1 */}
 },s->node);}

Value Interpreter::invoke(const FunctionPtr& f,const std::vector<Value>& args,ObjectPtr thisObject){if(f->native)return f->nativeCall(args);if(args.size()!=f->declaration.params.size())throw KymaError({"function '"+f->declaration.name+"' expects "+std::to_string(f->declaration.params.size())+" argument(s)",{1,1},false});auto old=environment;auto oldFlow=flow;flow={};environment=std::make_shared<Environment>(f->closure);if(thisObject){environment->define("self",Value(thisObject),false);if(thisObject->klass&&thisObject->klass->parent)environment->define("__parent_class",Value(thisObject->klass->parent),false);}for(size_t i=0;i<args.size();++i)environment->define(f->declaration.params[i].name,args[i],false);exec(f->declaration.body);Value result=flow.kind==Flow::Return?flow.value:Value();flow=oldFlow;environment=old;return result;}
Value Interpreter::eval(const ExprPtr& e){return std::visit([this](const auto& n)->Value{using T=std::decay_t<decltype(n)>;
 if constexpr(std::is_same_v<T,Literal>){switch(n.kind){case Literal::Kind::Null:return Value();case Literal::Kind::Bool:return Value(n.value=="true");case Literal::Kind::Int:return Value(static_cast<int64_t>(std::stoll(n.value)));case Literal::Kind::Float:return Value(std::stod(n.value));case Literal::Kind::String:{std::string s=n.value.substr(1,n.value.size()-2);return Value(s);}case Literal::Kind::Char:return Value(n.value.size()>2?n.value[1]:'\0');}}
 else if constexpr(std::is_same_v<T,Variable>)return environment->get(n.name).value;
 else if constexpr(std::is_same_v<T,SelfExpr>)return environment->get("self").value;
 else if constexpr(std::is_same_v<T,SuperExpr>)return environment->get("self").value;
 else if constexpr(std::is_same_v<T,Unary>){auto v=eval(n.right);if(n.op==TokenKind::Bang)return Value(!v.isTruthy());if(auto i=std::get_if<int64_t>(&v.data))return Value(-*i);if(auto d=std::get_if<double>(&v.data))return Value(-*d);throw KymaError({"unary '-' requires a number",{1,1},false});}
 else if constexpr(std::is_same_v<T,Binary>){if(n.op==TokenKind::AndAnd){auto l=eval(n.left);return l.isTruthy()?Value(eval(n.right).isTruthy()):Value(false);}if(n.op==TokenKind::OrOr){auto l=eval(n.left);return l.isTruthy()?Value(true):Value(eval(n.right).isTruthy());}return binary(n.op,eval(n.left),eval(n.right));}
 else if constexpr(std::is_same_v<T,Assign>){Value v=eval(n.value);if(auto x=std::get_if<Variable>(&n.target->node))environment->assign(x->name,v);else if(auto m=std::get_if<Member>(&n.target->node))setMember(m->object,m->name,v);else if(auto i=std::get_if<Index>(&n.target->node))setIndex(i->object,i->index,v);else throw KymaError({"invalid assignment target",{1,1},false});return v;}
 else if constexpr(std::is_same_v<T,Call>)return call(n,n.callee);
 else if constexpr(std::is_same_v<T,Member>)return getMember(n);
 else if constexpr(std::is_same_v<T,Index>){auto object=eval(n.object);auto index=eval(n.index);if(!std::holds_alternative<ArrayPtr>(object.data)||!std::holds_alternative<int64_t>(index.data))throw KymaError({"array indexing requires an integer index",{1,1},false});auto array=std::get<ArrayPtr>(object.data);auto i=std::get<int64_t>(index.data);if(i<0||static_cast<size_t>(i)>=array->elements.size())throw KymaError({"array index out of bounds",{1,1},false});return array->elements[static_cast<size_t>(i)];}
 else if constexpr(std::is_same_v<T,ArrayExpr>){auto array=objectHeap.allocateArray();for(auto&element:n.elements)array->elements.push_back(eval(element));return Value(array);}
 else if constexpr(std::is_same_v<T,NewExpr>){auto v=environment->get(n.className).value;if(!std::holds_alternative<ClassPtr>(v.data))throw KymaError({"'"+n.className+"' is not a class",{1,1},false});auto c=std::get<ClassPtr>(v.data);if(has(c->declaration.modifiers,"abstract"))throw KymaError({"cannot instantiate abstract class '"+n.className+"'",{1,1},false});auto o=objectHeap.allocate();o->klass=c;std::function<void(const ClassPtr&)> addFields=[&](const ClassPtr& k){if(k->parent)addFields(k->parent);for(auto& f:k->declaration.fields)if(!has(f.modifiers,"static"))o->fields[f.name]=f.initializer?eval(f.initializer):Value();};addFields(c);auto init=c->findMethod("init");if(init)invoke(init,[&]{std::vector<Value>a;for(auto&x:n.args)a.push_back(eval(x));return a;}(),o);else if(!n.args.empty())throw KymaError({"constructor takes no arguments",{1,1},false});return Value(o);}
 else if constexpr(std::is_same_v<T,ObjectExpr>){auto o=objectHeap.allocate();for(auto&f:n.fields)o->fields[f.name]=eval(f.value);return Value(o);}
 else if constexpr(std::is_same_v<T,IfExpr>){auto b=eval(n.condition).isTruthy()?n.thenBranch:n.elseBranch;auto* p=std::get_if<BlockStmt>(&b->node);if(!p){exec(b);return Value();}auto old=environment;environment=std::make_shared<Environment>(environment);for(auto&s:p->statements)exec(s);Value r=p->tail?eval(p->tail):Value();environment=old;return r;}
 else if constexpr(std::is_same_v<T,MatchExpr>){auto subject=eval(n.subject);for(auto&a:n.arms)if(a.wildcard||subject.equals(eval(a.pattern)))return eval(a.value);throw KymaError({"non-exhaustive match at runtime",{1,1},false});}
 else return Value();
 },e->node);}
Value Interpreter::binary(TokenKind op,const Value&a,const Value&b){if(op==TokenKind::EqualEqual)return Value(a.equals(b));if(op==TokenKind::BangEqual)return Value(!a.equals(b));if(op==TokenKind::Plus){if(std::holds_alternative<std::string>(a.data)||std::holds_alternative<std::string>(b.data))return Value(a.display()+b.display());if(std::holds_alternative<int64_t>(a.data)&&std::holds_alternative<int64_t>(b.data))return Value(std::get<int64_t>(a.data)+std::get<int64_t>(b.data));if((std::holds_alternative<int64_t>(a.data)||std::holds_alternative<double>(a.data))&&(std::holds_alternative<int64_t>(b.data)||std::holds_alternative<double>(b.data)))return Value((std::holds_alternative<int64_t>(a.data)?std::get<int64_t>(a.data):std::get<double>(a.data))+(std::holds_alternative<int64_t>(b.data)?std::get<int64_t>(b.data):std::get<double>(b.data)));throw KymaError({"'+' requires numbers or strings",{1,1},false});}bool nums=(std::holds_alternative<int64_t>(a.data)||std::holds_alternative<double>(a.data))&&(std::holds_alternative<int64_t>(b.data)||std::holds_alternative<double>(b.data));if(!nums)throw KymaError({"comparison requires numbers",{1,1},false});double x=std::holds_alternative<int64_t>(a.data)?std::get<int64_t>(a.data):std::get<double>(a.data),y=std::holds_alternative<int64_t>(b.data)?std::get<int64_t>(b.data):std::get<double>(b.data);switch(op){case TokenKind::Minus:return Value(x-y);case TokenKind::Star:return Value(x*y);case TokenKind::Slash:if(y==0)throw KymaError({"division by zero",{1,1},false});return Value(x/y);case TokenKind::Percent:return Value(static_cast<int64_t>(x)%static_cast<int64_t>(y));case TokenKind::Less:return Value(x<y);case TokenKind::LessEqual:return Value(x<=y);case TokenKind::Greater:return Value(x>y);case TokenKind::GreaterEqual:return Value(x>=y);default:throw KymaError({"unsupported operator",{1,1},false});}}
Value Interpreter::call(const Call& c,const ExprPtr& callee){Value v=eval(callee);std::vector<Value>a;for(auto&e:c.args)a.push_back(eval(e));if(!std::holds_alternative<FunctionPtr>(v.data))throw KymaError({"value of type '"+v.typeName()+"' is not callable",{1,1},false});return invoke(std::get<FunctionPtr>(v.data),a,std::get<FunctionPtr>(v.data)->boundThis);}
Value Interpreter::getMember(const Member&m){if(std::holds_alternative<SuperExpr>(m.object->node)){auto self=environment->get("self").value;auto o=std::get<ObjectPtr>(self.data);auto pc=environment->get("__parent_class").value;auto c=std::get<ClassPtr>(pc.data);auto f=c->findMethod(m.name);if(!f)throw KymaError({"parent has no member '"+m.name+"'",{1,1},false});auto bound=std::make_shared<Function>(*f);bound->boundThis=o;return Value(bound);}Value obj=eval(m.object);if(auto o=std::get_if<ObjectPtr>(&obj.data)){if(auto f=(*o)->fields.find(m.name);f!=(*o)->fields.end())return f->second;auto f=(*o)->klass?(*o)->klass->findMethod(m.name):nullptr;if(f){auto bound=std::make_shared<Function>(*f);bound->boundThis=*o;return Value(bound);}}if(auto c=std::get_if<ClassPtr>(&obj.data)){if(auto x=(*c)->staticFields.find(m.name);x!=(*c)->staticFields.end())return x->second;if(auto f=(*c)->findMethod(m.name);f&&has(f->declaration.modifiers,"static"))return Value(f);}throw KymaError({"unknown member '"+m.name+"'",{1,1},false});}
void Interpreter::setIndex(const ExprPtr&o,const ExprPtr&i,Value v){auto object=eval(o);auto index=eval(i);if(!std::holds_alternative<ArrayPtr>(object.data)||!std::holds_alternative<int64_t>(index.data))throw KymaError({"array indexing requires an integer index",{1,1},false});auto array=std::get<ArrayPtr>(object.data);auto position=std::get<int64_t>(index.data);if(position<0||static_cast<size_t>(position)>=array->elements.size())throw KymaError({"array index out of bounds",{1,1},false});array->elements[static_cast<size_t>(position)]=std::move(v);}
void Interpreter::setMember(const ExprPtr&o,const std::string&n,Value v){auto obj=eval(o);if(!std::holds_alternative<ObjectPtr>(obj.data))throw KymaError({"member assignment requires an object",{1,1},false});auto x=std::get<ObjectPtr>(obj.data);if(!x->fields.contains(n))throw KymaError({"unknown field '"+n+"' on closed object",{1,1},false});x->fields[n]=std::move(v);}
}
