#include "kyma/runtime.hpp"
#include "kyma/interpreter.hpp"
#include <cmath>
#include <sstream>

namespace kyma {
std::string Value::typeName() const { return std::visit([](const auto& v)->std::string {using T=std::decay_t<decltype(v)>;if constexpr(std::is_same_v<T,std::nullptr_t>)return "null";else if constexpr(std::is_same_v<T,bool>)return "bool";else if constexpr(std::is_same_v<T,int64_t>)return "int";else if constexpr(std::is_same_v<T,double>)return "float";else if constexpr(std::is_same_v<T,std::string>)return "str";else if constexpr(std::is_same_v<T,char>)return "char";else if constexpr(std::is_same_v<T,ObjectPtr>)return v&&v->klass?v->klass->declaration.name:"object";else if constexpr(std::is_same_v<T,ArrayPtr>)return "array";else if constexpr(std::is_same_v<T,FunctionPtr>)return "func";else return "class";},data); }
std::string Value::display() const { return std::visit([](const auto& v)->std::string {using T=std::decay_t<decltype(v)>;if constexpr(std::is_same_v<T,std::nullptr_t>)return "null";else if constexpr(std::is_same_v<T,bool>)return v?"true":"false";else if constexpr(std::is_same_v<T,int64_t>)return std::to_string(v);else if constexpr(std::is_same_v<T,double>){std::ostringstream o;o<<v;return o.str();}else if constexpr(std::is_same_v<T,std::string>)return v;else if constexpr(std::is_same_v<T,char>)return std::string(1,v);else if constexpr(std::is_same_v<T,ObjectPtr>)return "<"+(v&&v->klass?v->klass->declaration.name:"object")+">";else if constexpr(std::is_same_v<T,ArrayPtr>){std::string s="[";for(size_t i=0;i<v->elements.size();++i){if(i)s+=", ";s+=v->elements[i].display();}return s+"]";}else if constexpr(std::is_same_v<T,FunctionPtr>)return "<func>";else return "<class "+v->declaration.name+">";},data); }
bool Value::isTruthy() const {if(std::holds_alternative<std::nullptr_t>(data))return false;if(auto p=std::get_if<bool>(&data))return *p;if(auto p=std::get_if<int64_t>(&data))return *p!=0;if(auto p=std::get_if<double>(&data))return *p!=0.0;return true;}
bool Value::equals(const Value& o) const {if((std::holds_alternative<int64_t>(data)||std::holds_alternative<double>(data))&&(std::holds_alternative<int64_t>(o.data)||std::holds_alternative<double>(o.data))){double a=std::holds_alternative<int64_t>(data)?static_cast<double>(std::get<int64_t>(data)):std::get<double>(data);double b=std::holds_alternative<int64_t>(o.data)?static_cast<double>(std::get<int64_t>(o.data)):std::get<double>(o.data);return a==b;}if(data.index()!=o.data.index())return false;return std::visit([](const auto&a,const auto&b)->bool{using A=std::decay_t<decltype(a)>;using B=std::decay_t<decltype(b)>;if constexpr(std::is_same_v<A,B>){if constexpr(std::is_same_v<A,std::nullptr_t>)return true;else if constexpr(std::is_arithmetic_v<A>||std::is_same_v<A,std::string>)return a==b;else return a==b;}return false;},data,o.data);}
Environment::Environment(std::shared_ptr<Environment> p):enclosing(std::move(p)){}
void Environment::define(const std::string& n,Value v,bool m){if(values.contains(n))throw KymaError({"binding '"+n+"' is already declared in this scope",{1,1},false});values.emplace(n,Cell{std::move(v),m});}
Cell& Environment::get(const std::string& n){if(auto i=values.find(n);i!=values.end())return i->second;if(enclosing)return enclosing->get(n);throw KymaError({"undefined name '"+n+"'",{1,1},false});}
void Environment::assign(const std::string& n,Value v){auto i=values.find(n);if(i!=values.end()){if(!i->second.mutableBinding)throw KymaError({"cannot assign to immutable binding '"+n+"'",{1,1},false});i->second.value=std::move(v);return;}if(enclosing){enclosing->assign(n,std::move(v));return;}throw KymaError({"undefined name '"+n+"'",{1,1},false});}
std::shared_ptr<Environment> Environment::parent() const{return enclosing;}
FunctionPtr Class::findMethod(const std::string& n) const {if(auto i=methods.find(n);i!=methods.end())return i->second;return parent?parent->findMethod(n):nullptr;}
Value Function::call(const std::vector<Value>& args,Interpreter& interpreter){if(native)return nativeCall(args);return interpreter.invoke(std::make_shared<Function>(*this),args,boundThis);}
}
